services:
  server:
    image: server
    container_name: server
    build:
      context: serverOTP
    ports:
      - 8080:8080
    restart: no
    # volumes:
    #   - ./serverOTP/GTFS:/var/opentripplanner
    # networks:
    #   - distancesOTP

# networks:
#   distancesOTP:
#     driver: bridge

# volumes: