services:
  server:
    image: server
    container_name: server
    build:
      context: serverOTP
    ports:
      - 8000:8000
    restart: always
    # networks:
    #   - distancesOTP

# networks:
#   distancesOTP:
#     driver: bridge