---
title: "otp"
author: "Ruslan Basyrov"
date: "7/26/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gtfstools)
library(tidyverse)
library(rnaturalearth)
```

```{r}
gtfs_path <- file.path("/Users/johnnymosby/repos/thesis_demography/municipalitiesOTPDistances/serverOTP/GTFS")
```

```{r}
gtfs_files <- list.files(path = gtfs_path,
                         pattern = "*.gtfs.zip$",
                         full.names = TRUE)
```

```{r eval=FALSE}
# Reading the GTFS files into a list of R objects
gtfs_merged <- read_gtfs(gtfs_files) |> 
    remove_duplicates()
```


```{r}
# Filter by time of day
gtfs_filtered = read_gtfs(gtfs_files) |> 
    remove_duplicates() |> 
    filter_by_weekday("saturday") |>
    filter_by_time_of_day(from = "18:00:00",
                          to = "20:00:00")
```


```{r eval=FALSE}
{
    filename = paste(gtfs_path, "Austria_2024_saturday_evening_time.gtfs.zip", sep="/")
    write_gtfs(gtfs_filtered,
               filename)
}
```

```{r}
library(sf)
library(stringr)
library(opentripplanner) 
library(httr)

library(jsonlite)

year <- 2022

points <- read_sf(sprintf("/Users/johnnymosby/repos/thesis_demography/municipalitiesOSRMDistances/clientR/data/STATISTIK_AUSTRIA_GEM_MP_%s0101/", year),
                    options = "ENCODING=WINDOWS-1252")

points <- st_transform(points, 4326)
points_in_vorarlberg =  points[str_detect(points$g_id, "^8"),]

coordinates <- st_coordinates(points[, "geometry"]) |>
  as.data.frame()

durations = matrix(NA,
                   nrow = nrow(coordinates),
                   ncol = nrow(coordinates))
rownames(durations) = points$g_id
colnames(durations) = points$g_id

distances = matrix(NA,
                   nrow = nrow(coordinates),
                   ncol = nrow(coordinates))
rownames(distances) = points$g_id
colnames(distances) = points$g_id
```


```{r}
createQuery = function (from_latitude, from_longitude, to_latitude, to_longitude) {
    query <- sprintf('
query TransmodelExampleQuery {
  trip(
    from: {
      coordinates: {
        latitude: %.5f
        longitude: %.5f
      }
    }
    to: {
      coordinates: {
        latitude: %.5f
        longitude: %.5f
      }
    }
    dateTime: "2024-02-17T19:00:00+01:00"
  ) {
    tripPatterns {
      duration
      distance
      streetDistance
      expectedStartTime
      expectedEndTime
    }
  }
}
',
    from_latitude,
    from_longitude,
    to_latitude,
    to_longitude)

    return(query) 
}

```


```{r}

base_url <- "http://localhost:8080/otp/transmodel/v3"
response <- POST(base_url, 
                 body = list(query = query), 
                 encode = "json",
                 httr::add_headers(OTPTimeout = "180000"))


json = jsonlite::fromJSON(content(response, "text"))

if (length(json$data$trip$tripPatterns) == 0) {
    duration = NA
    distance = NA
} else {
    min_duration = which.min(json$data$trip$tripPatterns$duration)
    duration = json$data$trip$tripPatterns$duration[min_duration]
    distance = json$data$trip$tripPatterns$distance[min_duration]
}
```

```{r}
base_url <- "http://localhost:8080/otp/transmodel/v3"
n_expected_requests = sum(!is.na(distance_matrix))
n_current_requests = 0

for (i in 1:nrow(coordinates)) {
    for (j in 1:nrow(coordinates)) {
        if (is.na(distance_matrix[i, j])) {
            next
        }
        query = createQuery(coordinates[i, "Y"],
                            coordinates[i, "X"],
                            coordinates[j, "Y"],
                            coordinates[j, "X"])
        
        
        response <- httr::POST(base_url, 
                 body = list(query = query), 
                 encode = "json")
        
        json = jsonlite::fromJSON(content(response, "text", encoding="UTF-8"))
        
        if (length(json$data$trip$tripPatterns) == 0) {
            duration = NA
            distance = NA
        } else {
            min_duration = which.min(json$data$trip$tripPatterns$duration)
            duration = json$data$trip$tripPatterns$duration[min_duration]
            distance = json$data$trip$tripPatterns$distance[min_duration]
        }
        
        durations[i, j] = duration
        distances[i, j] = distance
        n_current_requests = n_current_requests + 1
        message(sprintf("i: %s j: %s progress: %.5f%%", 
                        i, 
                        j,
                        100 * n_current_requests / n_expected_requests),
                "\r",
                appendLF=FALSE)
        flush.console()
    }
}
```

```{r}
library(sf)
library(tidyverse)

distances <- t(apply(st_coordinates(points$geometry), 1, function(x) {
  st_distance(st_point(x), points)
}))

result_table <- as.data.frame(distances)
colnames(result_table) <- paste0("Point_", 1:ncol(result_table))
rownames(result_table) <- paste0("Point_", 1:nrow(result_table))

library(units)
distance_matrix = st_distance(points$geometry, points$geometry) |>
    drop_units()

distance_matrix[distance_matrix > 40000] = NA
```

```{r}
file_list <- list.files("/Users/johnnymosby/repos/thesis_demography/municipalitiesOSRMDistances/clientR/data/outputOSRM", full.names = TRUE)

for (file in file_list) {
    if (file == "/Users/johnnymosby/repos/thesis_demography/municipalitiesOSRMDistances/clientR/data/outputOSRM/distances_2020_20240405.csv" ||
        file == "/Users/johnnymosby/repos/thesis_demography/municipalitiesOSRMDistances/clientR/data/outputOSRM/durations_2020_20240405.csv") {
        next
    }
    print(file)
    table = read.csv(file)
    table = table[, -1]
    colnames(table) = points$g_id
    rownames(table) = points$g_id
    write.csv(table, file = file)
}
```


```{r}
otpcon <- otp_connect(check = FALSE)
```

```{r}
otp_plan(otpcon = otpcon,
         fromPlace = coordinates,
         toPlace = coordinates)
```

