---
title: "OSRM distances"
author: "Ruslan Basyrov"
date: "11/03/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{r}
library(sf)
library(osrm)
```


```{r}
shpFile = read_sf("/Users/johnnymosby/repos/thesis_demography/municipalitiesOSRMDistances/clientR/data/STATISTIK_AUSTRIA_GEM_MP_20200101/", options = "ENCODING=WINDOWS-1252")

shpFile <- st_transform(shpFile, 4326)
shpFile = shpFile[which(shpFile$g_name != "Schwanberg"),]
coordinates = st_coordinates(shpFile[, "geometry"]) |> 
    as.data.frame()

openstreetmapResponse = osrmTable(src = coordinates, 
                                  dst = coordinates, 
                                  measure = c('duration', 'distance'),
                                  osrm.server = "http://localhost:1234/")

durations = openstreetmapResponse[["durations"]]
distances = openstreetmapResponse[["distances"]]
datetime = format(Sys.time(), "%Y%m%d_%H%M")

write.csv(durations, paste("durations_", datetime, ".csv", sep = ""))
write.csv(distances, paste("distances_", datetime, ".csv", sep = ""))
```

