services:
  server:
    image: server
    container_name: server
    build:
      context: serverOSRM
    networks:
      - distances
    ports:
      - 1234:1234
    restart: always

  client:
    depends_on:
      - server
    image: client
    container_name: client
    build:
      context: clientR
    platform: linux/arm64
    volumes:
      - ./clientR:/var/distances
    networks:
      - distances
    restart: none

# volumes:
#   produced_distances:
#     driver_opts:
#       o: bind
#       type: none
#       device: ./clientR/data

networks:
  distances:
    name: distances
    driver: bridge