services:
  server:
    image: server
    container_name: server
    build:
      context: serverOSRM
    ports:
      - 5001:5000
    restart: always

  # client:
  #   depends_on:
  #     - server
  #   image: client
  #   container_name: client
  #   build:
  #     context: clientR
  #   volumes:
  #     - ./clientR:/var/distances
  #   networks:
  #     - distances
  #   restart: none

  clientosrm:
    image: osrm/osrm-frontend
    depends_on:
      - server
    environment:
      - OSRM_BACKEND=http://localhost:5001
    ports:
      - 9966:9966
#   map:
#     image: overv/openstreetmap-tile-server
#     volumes:
#       - osm-data:/data/database/
#     ports:
#       - "8080:80"
#     command: "run"

# volumes:
#   osm-data:
#     external: true

networks:
  distances:
    driver: bridge