services:
  server:
    image: server
    container_name: server
    build:
      context: serverOSRM
    networks:
      - distances
    restart: always
  
  client:
    depends_on:
      - server
    image: client
    container_name: client
    build:
      context: clientR
    volumes:
      - produced_distances:/var/distances
    networks:
      - distances
    restart: always

  volumes:
    produced_distances:
      driver_opts:
        o: bind
        type: none
        device: clientR/data

  networks:
    distances:
      name: distances
      driver: bridge