services:
  server:
    image: server
    container_name: server
    build:
      context: serverOSRM
    networks:
      - distances
    restart: always

  client:
    depends_on:
      - server
    image: client
    container_name: client
    build:
      context: clientR
    platform: linux/arm64
    volumes:
      - ./clientR:/var/distances
    networks:
      - distances
    restart: none

networks:
  distances:
    driver: bridge